### PR TITLE
bugfixes and enhancements

### PR DESCRIPTION
**Pull request by chassing**
- fixed install dependencies
- core enhancements
  - /me support
  - /nick support
  - get configuration via environment

### CODE REVIEW

**Comment by brunobord** [comment]
well... looks like a great PR, many thanks. I'm a bit busy at the moment (son being born last thursday). will check it out more precisely a bit later, sorry for the delay.

**Comment by brunobord** [comment]
I've got a few questions and remarks about this pull request, if you don't mind.

First of all, you seem to add a lot of new features / fixes in this (now) BIG pull request. That'd be perfectly fine if I was okay with all these modifications.
Adding more and more edits to this pull requests, unfortunately, is adding more confusion about what I think would be great for the "upstream" bot, and what I think wouldn't be so great.

I'm not a Github-Pull-Request expert, so I don't know if it's easy, but wouldn't it be possible to split this big pull request into several smaller ones, one per new feature, for example?

**Comment by brunobord** [comment]
to help you out... what I think is great :
- argparse dependency fix
- environment variable config
- don't die in case of exceptions
- IRC server password support
- reconnecting (PONG) - I thought this one was already working
- SSL Support

Those that needs to be discussed (my fault, I may not understand your point)
- /me support
- /nick support

**Comment by chassing** [comment]
wow, i see what you mean with a 'big pull request'. that was not my intention :( i thought the first 7 commits 6 days ago are the PR, not all commits in the last days.
i will close this PR and try it again with smaller ones, but i'm also not a pull request hero ;)

**Comment by brunobord** [comment]
cool, thanks a million.

**Pull request closed without merging**
